# Generated by Django 4.1.7 on 2023-03-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptostego', '0003_alter_image_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('audio_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
